trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: go build
  displayName: 'Build'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
